# Generated by Django 5.2.5 on 2025-10-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
